version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: phpunit/phpunit
    versions:
    - ">= 8.a, < 9"
  - dependency-name: phpunit/phpunit
    versions:
    - ">= 9.a, < 10"
  - dependency-name: symfony/browser-kit
    versions:
    - ">= 5.0.a, < 5.1"
  - dependency-name: symfony/browser-kit
    versions:
    - ">= 5.a, < 6"
  - dependency-name: symfony/css-selector
    versions:
    - ">= 5.0.a, < 5.1"
  - dependency-name: symfony/css-selector
    versions:
    - "> 5.2.0, < 5.3"
  - dependency-name: twig/twig
    versions:
    - "> 2.14.1, < 2.15"
  - dependency-name: twig/twig
    versions:
    - ">= 3.a, < 4"
  - dependency-name: symfony/browser-kit
    versions:
    - 4.4.20
